version: "3"
services:

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: super_secret_password
      POSTGRES_USER: super_user
    restart: always
  app:
    depends_on:
      - postgres
    build: ./contactsapi
    restart: on-failure
    ports:
      - "8000:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=super_user
      - SPRING_DATASOURCE_PASSWORD=super_secret_password
    tty: true